# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Microsoft.Aspire
PackageVersion: 13.6.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: aspire.exe
  PortableCommandAlias: aspire
InstallModes:
- silent
UpgradeBehavior: uninstallPrevious
Commands:
- aspire
Installers:
- Architecture: x64
  InstallerUrl: https://ci.dot.net/public/aspire/13.6.1-preview.1.26506.6/aspire-cli-win-x64-13.6.1.zip
  InstallerSha256: FF3894426C83FCBCB5215E592D34D9F7ACF3F5DEFCE34B635591DB915903AD51
- Architecture: arm64
  InstallerUrl: https://ci.dot.net/public/aspire/13.6.1-preview.1.26506.6/aspire-cli-win-arm64-13.6.1.zip
  InstallerSha256: B9B4067C2DC01A9D529C3C76503D79E5AD0BBA08D3F4C7C9FFF2D0D1E5F44EF9
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-07
